### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by mareksuscak** [comment]
@mllrsohn would you consider accepting this PR and releasing a new version so we can depend on this package again?

**Comment by jrbenito** [comment]
Did anyone test this PR?

**Comment by mareksuscak** [comment]
@jrbenito we've upgraded to grunt 1.x and I believe it still works

**Review by jrbenito — APPROVED** [review]

**Comment by mareksuscak** [comment]
But of course, it whines about missing peer dependency so it would be cool if we could accept this PR and release a new version. Otherwise, we have to start depending on a [namespaced fork](https://www.npmjs.com/package/@jwalsh/grunt-invalidate-cloudfront).

**Comment by steffenmllr** [comment]
Sorry for taken so long. I don't use grunt anymore. @mareksuscak would you be interested in maintaining this module ?

**Comment by mareksuscak** [comment]
No problem @steffenmllr. I don't use grunt personally, too. Just my company uses it. I've seen some existing forks and the most up-to-date was https://github.com/jwalsh/grunt-invalidate-cloudfront so maybe @jwalsh could be interested in taking it over?

**Comment by jwalsh** [comment]
@steffenmllr @mareksuscak : There's a project I maintain that still uses this; I should be able to maintain it.

Will  check out out the open PRs and issues...

**Comment by steffenmllr** [comment]
@jwalsh Great thank you! I've given you write access to this repo and publishing rights to npm

**Pull request merged**
